# Generated by Django 6.0.6 on 2026-06-27 21:08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Task Details'),
        ),
    ]
