# Generated by Django 6.0.6 on 2026-06-28 15:41

import myApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_project_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.FileField(blank=True, null=True, upload_to='projects/', validators=[myApp.validators.validate_file_size]),
        ),
    ]
